### ISSUE TITLE
How do you make these?

### ISSUE THREAD

**Issue by SavvySeventy7** [DragonDev07/Wallpapers#2]
I was wondering how you made these themed wallpaper? I ask only because I would really like to make some wallpapers for my self based on the Rosepine theme

**Comment by teowelton** [comment]
I typically just color correct images to fit the theme. There are many different tools out there to do this, but the one I like to use is [lutgen-rs](https://github.com/ozwaldorf/lutgen-rs). Another great alternative is [farbenfroh.io](https://farbenfroh.io/), which even has rose pine built in!

**Comment by SavvySeventy7** [comment]
Thank you so much! lutgen-rs is the way to go with the Rosepine palette.
